### ISSUE TITLE
Whether vue3 version is supported or not, tempalte will not work

### ISSUE THREAD

**Issue by a857430369** [afterwind-io/preprocessor-loader#26]
<template>
<--  #!if xxxx -->
test
<--  #!endif -->
</tempalte>

As described above
It doen‘t work

**Comment by afterwind-io** [comment]
tl;dr
Q: Is Vue3 supported?
A: Yes.

The loader is designed for processing the text as a **Webpack Loader**. So it is irrelevant to the file type nor the frontend framework.

If you are working with `@vue/cli` (tested with 5.0.1):

```js
//vue.config.js

const { defineConfig } = require("@vue/cli-service");
module.exports = defineConfig({
  transpileDependencies: true,
  chainWebpack: (config) => {
    config.module
      .rule("vue")
      .test(/\.vue$/)
      .use("webpack-preprocessor-loader")
      .loader("webpack-preprocessor-loader")
      .options({
        params: {
          oops: false,
        },
      })
      .end();
  },
});
```

```vue
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <!-- #!if oops -->
  <h1> This heading should be hidden. </h1>
  <!-- #!endif -->
  <HelloWorld msg="Welcome to Your Vue.js App"/>
</template>
```

Read the doc:
https://cli.vuejs.org/guide/webpack.html#adding-a-new-loader
https://github.com/neutrinojs/webpack-chain#getting-started
