### ISSUE TITLE
请教下，你的 README  中的 Badge 是如何自动生成的呢？

### ISSUE THREAD

**Issue by kaysonwu** [afterwind-io/preprocessor-loader#8]
RT

**Comment by kaysonwu** [comment]
@afterwind-io

**Comment by afterwind-io** [comment]
@kaysonwu 
可以参考README原文下方的链接。badge的功能是 https://shields.io/ 提供的开放api，具体可参考对应的文档。

**Comment by kaysonwu** [comment]
原来你用的是 SVG，并且把它放到了 README 的最下面，我还以为是自动识别！谢谢
